/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/drafts` | `/drafts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/submissions` | `/submissions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sync` | `/sync`; params?: Router.UnknownInputParams; } | { pathname: `/form/[type]`, params: Router.UnknownInputParams & { type: string | number; } } | { pathname: `/submission/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/drafts` | `/drafts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/submissions` | `/submissions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sync` | `/sync`; params?: Router.UnknownOutputParams; } | { pathname: `/form/[type]`, params: Router.UnknownOutputParams & { type: string; } } | { pathname: `/submission/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/drafts${`?${string}` | `#${string}` | ''}` | `/drafts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/forms${`?${string}` | `#${string}` | ''}` | `/forms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/submissions${`?${string}` | `#${string}` | ''}` | `/submissions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sync${`?${string}` | `#${string}` | ''}` | `/sync${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/drafts` | `/drafts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/submissions` | `/submissions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sync` | `/sync`; params?: Router.UnknownInputParams; } | `/form/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/submission/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/form/[type]`, params: Router.UnknownInputParams & { type: string | number; } } | { pathname: `/submission/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
